title: 🎉Happy Birthday🎉
description: > # this means to ignore newlines until "baseurl:"
  Wishing you a truly wonderful celebration!
permalink: ':title/'
baseurl: "/HappyBdayJaeJae/" # the subpath of your site, e.g. /blog
url: "https://wonjae2025.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# url: "http://localhost:4000"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: JAEJAE # add your name
author-img: profile.jpg # add your photo

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
# analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
